
FROM python:3.8

ENV PYTHONUNBUFFERED 1
RUN useradd -ms /bin/bash celeryuser
WORKDIR /app
COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip --disable-pip-version-check install -r requirements.txt

COPY . /app/
USER celeryuser

CMD celery -A config worker --loglevel=info --max-tasks-per-child 1000 --max-memory-per-child 1000000
